services:
  studybridge:
    build: .
    container_name: studybridge_bot
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - bots_default

networks:
  bots_default:
    external: true
